"""initial schema

Revision ID: 4be78736bd87
Revises: 
Create Date: 2026-02-07 17:16:57.613860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4be78736bd87'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('role', sa.Enum('admin', 'creator', 'user', name='userrole'), nullable=False),
    sa.Column('is_public_profile', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('creator_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='requeststatus'), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creator_requests_created_at'), 'creator_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_creator_requests_status'), 'creator_requests', ['status'], unique=False)
    op.create_index(op.f('ix_creator_requests_user_id'), 'creator_requests', ['user_id'], unique=False)
    op.create_table('ratings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.Enum('movie', 'tv', name='mediatype'), nullable=False),
    sa.Column('rating', sa.Enum('skip', 'timepass', 'go_for_it', 'perfection', name='ratingvalue'), nullable=False),
    sa.Column('rated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tmdb_id', 'media_type', name='unique_user_rating')
    )
    op.create_index(op.f('ix_ratings_rated_at'), 'ratings', ['rated_at'], unique=False)
    op.create_index(op.f('ix_ratings_tmdb_id'), 'ratings', ['tmdb_id'], unique=False)
    op.create_index(op.f('ix_ratings_user_id'), 'ratings', ['user_id'], unique=False)
    op.create_table('watchlist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.Enum('movie', 'tv', name='mediatype'), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tmdb_id', 'media_type', name='unique_user_media')
    )
    op.create_index(op.f('ix_watchlist_added_at'), 'watchlist', ['added_at'], unique=False)
    op.create_index(op.f('ix_watchlist_tmdb_id'), 'watchlist', ['tmdb_id'], unique=False)
    op.create_index(op.f('ix_watchlist_user_id'), 'watchlist', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_user_id'), table_name='watchlist')
    op.drop_index(op.f('ix_watchlist_tmdb_id'), table_name='watchlist')
    op.drop_index(op.f('ix_watchlist_added_at'), table_name='watchlist')
    op.drop_table('watchlist')
    op.drop_index(op.f('ix_ratings_user_id'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_tmdb_id'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_rated_at'), table_name='ratings')
    op.drop_table('ratings')
    op.drop_index(op.f('ix_creator_requests_user_id'), table_name='creator_requests')
    op.drop_index(op.f('ix_creator_requests_status'), table_name='creator_requests')
    op.drop_index(op.f('ix_creator_requests_created_at'), table_name='creator_requests')
    op.drop_table('creator_requests')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
