"""Add user roles and creator requests

Revision ID: 742c53764c0d
Revises: add_email_verification
Create Date: 2026-01-26 16:45:09.267093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '742c53764c0d'
down_revision: Union[str, None] = 'add_email_verification'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create the enum type first
    userrole_enum = sa.Enum('admin', 'creator', 'user', name='userrole', create_type=True)
    userrole_enum.create(op.get_bind(), checkfirst=True)
    
    # Add columns as nullable first
    op.add_column('users', sa.Column('role', sa.Enum('admin', 'creator', 'user', name='userrole'), nullable=True))
    op.add_column('users', sa.Column('is_public_profile', sa.Boolean(), nullable=True))
    
    # Set default values for existing rows
    op.execute("UPDATE users SET role = 'user' WHERE role IS NULL")
    op.execute("UPDATE users SET is_public_profile = false WHERE is_public_profile IS NULL")
    
    # Make columns non-nullable
    op.alter_column('users', 'role', nullable=False)
    op.alter_column('users', 'is_public_profile', nullable=False)
    
    # Create creator_requests table
    op.create_table('creator_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='requeststatus'), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('creator_requests')
    op.drop_column('users', 'is_public_profile')
    op.drop_column('users', 'role')
    
    # Drop enum types
    sa.Enum(name='userrole').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='requeststatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
